### ISSUE TITLE
Petlib cannot be installed systemwide, else it tries to create cache files in /usr/lib/python3.4/site-packages/petlib/...

### ISSUE THREAD

**Issue by Sidnioulz** [gdanezis/petlib#1] opened 2015-01-13 17:27 UTC
Petlib crashes when installed systewide, because it tries to create cache files in /usr/lib/python3.4/site-packages/petlib/...  Please ensure that petlib identifies a read-write area to create cache files into, rather than in its install location which should be treated as read-only.

Suggested locations:
$XDG_CACHE_HOME/petlib
$HOME/.cache/petlib
/tmp/petlib

**Comment by gdanezis** [comment] 2015-01-13 18:51
Aha. Nice catch -- I did put off taking care of this so far. The issue is that the library C bindings were not compiled at setup / install time, but only when it was first ran. As a result the binaries were placed in a folder that was not writable.
I believe the issue should be fixed by importing 'petlib.bindings' in the setup script in the latest commit. However, I am testing a bit more before closing the issue to ensure this takes care of it.

**Comment by gdanezis** [comment] 2015-01-16 21:51
Great -- confirmed in person the issue has been fixed. Thanks Steve!

**Closed by gdanezis** 2015-01-16 21:51 UTC

**Comment by Sidnioulz** [comment] 2015-01-16 22:44
Thanks for fixing it!
